# Generated by Django 5.1.10 on 2025-07-17 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = []
