# Generated by Django 5.1.10 on 2025-07-17 15:43

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20250717_1843"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BiometricSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "verification_method",
                    models.CharField(default="face_recognition", max_length=50),
                ),
                ("confidence_score", models.FloatField()),
                ("quality_score", models.FloatField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("location", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="DeviceToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True)),
                (
                    "device_id",
                    models.CharField(
                        help_text="Unique device identifier", max_length=100
                    ),
                ),
                (
                    "device_info",
                    models.JSONField(
                        default=dict, help_text="Device metadata (OS, model, etc)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("last_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("last_location", models.JSONField(blank=True, null=True)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("biometric_verified", models.BooleanField(default=False)),
                ("biometric_verified_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("email_sent", models.BooleanField(default=False)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TokenRefreshLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_expires_at", models.DateTimeField()),
                ("new_expires_at", models.DateTimeField()),
                ("refreshed_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-refreshed_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Hourly rate for hourly employees",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="monthly_salary",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Monthly salary for full-time employees",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("employee", "Employee"),
                    ("accountant", "Accountant"),
                    ("admin", "Administrator"),
                ],
                default="employee",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Django user account (created when invitation is accepted)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(
                help_text="Employee's email address", max_length=254, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("full_time", "Full Time"),
                    ("part_time", "Part Time"),
                    ("hourly", "Hourly"),
                    ("contract", "Contract"),
                ],
                default="full_time",
                help_text="Type of employment",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="first_name",
            field=models.CharField(help_text="Employee's first name", max_length=50),
        ),
        migrations.AlterField(
            model_name="employee",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether the employee is currently active"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_name",
            field=models.CharField(help_text="Employee's last name", max_length=50),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Phone number in international format",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["email"], name="users_emplo_email_e2f2c3_idx"),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["is_active"], name="users_emplo_is_acti_5d4e2d_idx"
            ),
        ),
        migrations.AddField(
            model_name="devicetoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="biometricsession",
            name="device_token",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.devicetoken"
            ),
        ),
        migrations.AddField(
            model_name="employeeinvitation",
            name="employee",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitation",
                to="users.employee",
            ),
        ),
        migrations.AddField(
            model_name="employeeinvitation",
            name="invited_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tokenrefreshlog",
            name="device_token",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.devicetoken"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="devicetoken",
            unique_together={("user", "device_id")},
        ),
        migrations.AddIndex(
            model_name="employeeinvitation",
            index=models.Index(fields=["token"], name="users_emplo_token_0c2e11_idx"),
        ),
        migrations.AddIndex(
            model_name="employeeinvitation",
            index=models.Index(
                fields=["expires_at"], name="users_emplo_expires_da7a25_idx"
            ),
        ),
    ]
