# Generated by Django 5.1.6 on 2025-05-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_updated_at_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(help_text="Employee's email address", max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('monthly', 'Monthly Salary'), ('hourly', 'Hourly Wage'), ('contract', 'Contract Work')], default='hourly', help_text='Type of employment contract', max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(help_text="Employee's first name", max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the employee is currently active'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(help_text="Employee's last name", max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number in international format', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['email'], name='users_emplo_email_e2f2c3_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['is_active'], name='users_emplo_is_acti_5d4e2d_idx'),
        ),
    ]
