# Generated by Django 5.1.6 on 2025-06-01 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_employee_options_alter_employee_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate for hourly employees', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('accountant', 'Accountant'), ('admin', 'Administrator')], default='employee', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('hourly', 'Hourly'), ('contract', 'Contract')], default='full_time', help_text='Type of employment', max_length=10),
        ),
    ]
