# Generated by Django 5.1.12 on 2025-10-30 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_change_user_onetoone_to_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='previous_token',
            field=models.CharField(blank=True, db_index=True, help_text='Previous token before rotation (for replay attack detection)', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='previous_token_expires_at',
            field=models.DateTimeField(blank=True, help_text='Grace period for previous token (allows for clock skew)', null=True),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='rotation_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this token has been rotated'),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['token'], name='users_devic_token_271e2e_idx'),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['previous_token'], name='users_devic_previou_34112c_idx'),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['user', 'device_id', 'is_active'], name='users_devic_user_id_ab652f_idx'),
        ),
    ]
