# Generated by Django 5.1.6 on 2025-06-05 21:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_employee_hourly_rate_employee_role_employee_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('device_id', models.CharField(help_text='Unique device identifier', max_length=100)),
                ('device_info', models.JSONField(default=dict, help_text='Device metadata (OS, model, etc)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_location', models.JSONField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('biometric_verified', models.BooleanField(default=False)),
                ('biometric_verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'device_id')},
            },
        ),
        migrations.CreateModel(
            name='BiometricSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('verification_method', models.CharField(default='face_recognition', max_length=50)),
                ('confidence_score', models.FloatField()),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.devicetoken')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TokenRefreshLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_expires_at', models.DateTimeField()),
                ('new_expires_at', models.DateTimeField()),
                ('refreshed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.devicetoken')),
            ],
            options={
                'ordering': ['-refreshed_at'],
            },
        ),
    ]
