# Generated by Django 5.1.12 on 2025-11-17 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_database_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='devicetoken',
            name='users_devic_user_id_ab652f_idx',
        ),
        migrations.RenameIndex(
            model_name='devicetoken',
            new_name='dev_token_token_idx',
            old_name='users_devic_token_271e2e_idx',
        ),
        migrations.RenameIndex(
            model_name='devicetoken',
            new_name='dev_token_prev_idx',
            old_name='users_devic_previou_34112c_idx',
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='previous_token',
            field=models.CharField(blank=True, help_text='Previous token before rotation (for replay attack detection)', max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['user'], name='dev_token_user_idx'),
        ),
    ]
