# Production docker-compose configuration
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

services:
  web:
    environment:
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=myhours.settings_prod
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn myhours.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    restart: unless-stopped

  celery:
    environment:
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=myhours.settings_prod
    restart: unless-stopped

  # Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: myhours_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./staticfiles:/var/www/static:ro
      - ./media:/var/www/media:ro
    depends_on:
      - web
    networks:
      - myhours_network
    restart: unless-stopped