services:
  # Django Web Application
  web:
    build: .
    container_name: myhours_web
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
      - ./staticfiles:/app/staticfiles
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://myhours_user:secure_password_123@postgres:5432/myhours_db
      - REDIS_URL=redis://:redis_password_123@redis:6379/0
      - MONGO_CONNECTION_STRING=mongodb://mongodb:27017/
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=biometrics_db
      - MONGO_DB_NAME=biometrics_db
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    networks:
      - myhours_network
    healthcheck:
      test: ["CMD", "python", "manage.py", "check", "--deploy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  # Celery Worker
  celery:
    build: .
    container_name: myhours_celery
    restart: always
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://myhours_user:secure_password_123@postgres:5432/myhours_db
      - REDIS_URL=redis://:redis_password_123@redis:6379/0
      - MONGO_CONNECTION_STRING=mongodb://mongodb:27017/
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=biometrics_db
      - MONGO_DB_NAME=biometrics_db
    depends_on:
      - postgres
      - redis
      - mongodb
    networks:
      - myhours_network
    command: celery -A myhours worker -l info

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: myhours_postgres
    restart: always
    environment:
      POSTGRES_DB: myhours_db
      POSTGRES_USER: myhours_user
      POSTGRES_PASSWORD: secure_password_123
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - myhours_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myhours_user -d myhours_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: myhours_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - myhours_network
    command: redis-server --appendonly yes --requirepass redis_password_123
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis_password_123", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MongoDB for biometrics (no auth for development)
  mongodb:
    image: mongo:7
    container_name: myhours_mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: biometrics_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - myhours_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  mongodb_data:
    driver: local
  media_data:
    driver: local
  static_data:
    driver: local

networks:
  myhours_network:
    driver: bridge