# Generated by Django 5.1.10 on 2025-07-27 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worklog",
            name="employee",
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
        migrations.DeleteModel(
            name="WorkLog",
        ),
    ]
