# Generated by Django 5.1.6 on 2025-02-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('monthly', 'Monthly Salary'), ('hourly', 'Hourly Wage'), ('contract', 'Contract Work')], default='hourly', max_length=10),
        ),
    ]
