# Generated by Django 5.1.6 on 2025-02-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employee_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='employment_type',
            field=models.CharField(choices=[('monthly', 'Monthly Salary'), ('hourly', 'Hourly Wage')], default='monthly', max_length=10),
        ),
    ]
