# Generated by Django 5.1.6 on 2025-02-28 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_salary_employment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='employment_type',
        ),
    ]
