# Generated by Django 5.1.6 on 2025-03-07 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_salary_employment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklog',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='WorkLog',
        ),
    ]
