# Generated by Django 5.1.6 on 2025-06-02 19:50

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BiometricAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("attempts_count", models.IntegerField(default=0)),
                ("last_attempt", models.DateTimeField(auto_now=True)),
                ("blocked_until", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Biometric Attempt",
                "verbose_name_plural": "Biometric Attempts",
                "db_table": "biometric_attempts",
            },
        ),
        migrations.CreateModel(
            name="BiometricLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("check_in", "Check In"),
                            ("check_out", "Check Out"),
                            ("registration", "Registration"),
                            ("failed", "Failed Attempt"),
                        ],
                        max_length=20,
                    ),
                ),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("device_info", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("processing_time_ms", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biometric_logs",
                        to="users.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Biometric Log",
                "verbose_name_plural": "Biometric Logs",
                "db_table": "biometric_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BiometricProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("embeddings_count", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("mongodb_id", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biometric_profile",
                        to="users.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Biometric Profile",
                "verbose_name_plural": "Biometric Profiles",
                "db_table": "biometric_profiles",
            },
        ),
        migrations.CreateModel(
            name="FaceQualityCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("face_detected", models.BooleanField(default=False)),
                ("face_count", models.IntegerField(default=0)),
                ("brightness_score", models.FloatField(blank=True, null=True)),
                ("blur_score", models.FloatField(blank=True, null=True)),
                ("face_size_ratio", models.FloatField(blank=True, null=True)),
                ("eye_visibility", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "biometric_log",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_check",
                        to="biometrics.biometriclog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Face Quality Check",
                "verbose_name_plural": "Face Quality Checks",
                "db_table": "face_quality_checks",
            },
        ),
        migrations.AddIndex(
            model_name="biometriclog",
            index=models.Index(
                fields=["employee", "-created_at"],
                name="biometric_l_employe_1d560c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="biometriclog",
            index=models.Index(
                fields=["action", "-created_at"], name="biometric_l_action_c27320_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="biometriclog",
            index=models.Index(
                fields=["success", "-created_at"], name="biometric_l_success_7002d1_idx"
            ),
        ),
    ]
