# Generated by Django 5.1.10 on 2025-07-23 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0003_alter_worklog_options_and_more'),
    ]

    operations = [
    ]
