# Generated by Django 5.1.12 on 2025-10-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_change_user_onetoone_to_fk"),
        ("worktime", "0005_add_location_and_break_fields"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="worklog",
            index=models.Index(
                fields=["check_out"], name="worktime_wo_check_o_e1bec4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="worklog",
            index=models.Index(
                fields=["employee", "check_in", "check_out"],
                name="worktime_wo_employe_b77c9c_idx",
            ),
        ),
    ]
