# Generated by Django 5.1.12 on 2025-10-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_change_user_onetoone_to_fk'),
        ('worktime', '0006_add_checkout_indexes'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='worklog',
            constraint=models.UniqueConstraint(condition=models.Q(('check_out__isnull', True), ('is_deleted', False)), fields=('employee',), name='unique_active_checkin_per_employee'),
        ),
    ]
