# Generated by Django 5.1.10 on 2025-07-24 18:20

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payroll",
            "0002_remove_salary_bonus_remove_salary_calculated_salary_and_more",
        ),
        ("users", "0003_biometricsession_devicetoken_employeeinvitation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyPayrollCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_date", models.DateField(db_index=True)),
                (
                    "regular_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "overtime_hours_1",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="First 2 overtime hours at 125%",
                        max_digits=5,
                    ),
                ),
                (
                    "overtime_hours_2",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Additional overtime hours at 150%",
                        max_digits=5,
                    ),
                ),
                (
                    "night_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "regular_pay",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "overtime_pay_1",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "overtime_pay_2",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "total_pay",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("is_holiday", models.BooleanField(default=False)),
                ("is_sabbath", models.BooleanField(default=False)),
                ("is_night_shift", models.BooleanField(default=False)),
                (
                    "holiday_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "calculation_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detailed breakdown of calculation",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "calculated_by_service",
                    models.CharField(
                        default="EnhancedPayrollCalculationService", max_length=50
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_payroll_calculations",
                        to="users.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Payroll Calculation",
                "verbose_name_plural": "Daily Payroll Calculations",
                "ordering": ["-work_date"],
                "indexes": [
                    models.Index(
                        fields=["employee", "work_date"],
                        name="payroll_dai_employe_7321f2_idx",
                    ),
                    models.Index(
                        fields=["work_date"], name="payroll_dai_work_da_cde720_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="payroll_dai_created_8cfea4_idx"
                    ),
                ],
                "unique_together": {("employee", "work_date")},
            },
        ),
        migrations.CreateModel(
            name="MonthlyPayrollSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                (
                    "total_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "regular_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "holiday_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "sabbath_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "base_pay",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "overtime_pay",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "holiday_pay",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "sabbath_pay",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "total_gross_pay",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("worked_days", models.IntegerField(default=0)),
                ("compensatory_days_earned", models.IntegerField(default=0)),
                ("calculation_date", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "calculation_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional calculation metadata",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_payroll_summaries",
                        to="users.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Monthly Payroll Summary",
                "verbose_name_plural": "Monthly Payroll Summaries",
                "ordering": ["-year", "-month"],
                "indexes": [
                    models.Index(
                        fields=["employee", "year", "month"],
                        name="payroll_mon_employe_938529_idx",
                    ),
                    models.Index(
                        fields=["year", "month"], name="payroll_mon_year_940e5f_idx"
                    ),
                    models.Index(
                        fields=["calculation_date"],
                        name="payroll_mon_calcula_b14ccc_idx",
                    ),
                ],
                "unique_together": {("employee", "year", "month")},
            },
        ),
    ]
