# Generated by Django 5.1.6 on 2025-03-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_remove_salary_bonus_remove_salary_calculated_salary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compensatoryday',
            options={'ordering': ['-date_earned'], 'verbose_name': 'Compensatory Day', 'verbose_name_plural': 'Compensatory Days'},
        ),
        migrations.AlterField(
            model_name='compensatoryday',
            name='reason',
            field=models.CharField(choices=[('shabbat', 'Work on Shabbat'), ('holiday', 'Work on Holiday')], max_length=50),
        ),
    ]
