# Generated by Django 5.1.6 on 2025-04-02 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_compensatoryday_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, help_text='Monthly rate or total project cost', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='salary',
            name='calculation_type',
            field=models.CharField(choices=[('hourly', 'hourly'), ('monthly', 'monthly'), ('project', 'project')], default='hourly', max_length=10),
        ),
        migrations.AlterField(
            model_name='salary',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, help_text='Hourly rate', max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
