# Generated by Django 5.1.10 on 2025-07-27 14:01

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0003_dailypayrollcalculation_monthlypayrollsummary"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailypayrollcalculation",
            name="total_gross_pay",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Full gross payment including base salary for monthly employees",
                max_digits=12,
            ),
        ),
    ]
