# Generated by Django 5.1.10 on 2025-07-27 17:19

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0004_add_total_gross_pay_to_daily_calculations"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailypayrollcalculation",
            name="base_pay",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Base payment: hours × hourly_rate for all employee types",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="dailypayrollcalculation",
            name="bonus_pay",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="All bonus payments: overtime, sabbath, holiday premiums",
                max_digits=12,
            ),
        ),
    ]
