# Generated by Django 5.1.10 on 2025-08-04 15:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_add_base_pay_bonus_pay_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypayrollcalculation',
            name='sabbath_overtime_hours_1',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='First 2 sabbath overtime hours at 175%', max_digits=5),
        ),
        migrations.AddField(
            model_name='dailypayrollcalculation',
            name='sabbath_overtime_hours_2',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Additional sabbath overtime hours at 200%', max_digits=5),
        ),
        migrations.AddField(
            model_name='dailypayrollcalculation',
            name='sabbath_overtime_pay_1',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Payment for first 2 sabbath overtime hours at 175%', max_digits=10),
        ),
        migrations.AddField(
            model_name='dailypayrollcalculation',
            name='sabbath_overtime_pay_2',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Payment for additional sabbath overtime hours at 200%', max_digits=10),
        ),
    ]
