# Generated by Django 5.1.6 on 2025-08-04 17:48

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0006_add_sabbath_overtime_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailypayrollcalculation",
            name="sabbath_regular_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Regular hours worked during Sabbath at 150%",
                max_digits=5,
            ),
        ),
    ]
