# Generated by Django 5.1.6 on 2025-08-11 19:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0007_add_sabbath_regular_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailypayrollcalculation",
            name="is_test",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="dailypayrollcalculation",
            name="night_pay",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Night shift pay (for test compatibility)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="dailypayrollcalculation",
            name="overtime_pay",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Total overtime pay (for test compatibility)",
                max_digits=10,
            ),
        ),
    ]
