# Generated by Django 5.1.6 on 2025-08-12 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0008_add_test_compatibility_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailypayrollcalculation",
            name="night_pay",
        ),
        migrations.RemoveField(
            model_name="dailypayrollcalculation",
            name="overtime_pay",
        ),
    ]
