# Generated by Django 5.1.6 on 2025-08-12 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0009_remove_dailypayrollcalculation_night_pay_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailypayrollcalculation",
            name="is_test",
        ),
    ]
