# Generated by Django 5.1.6 on 2025-08-12 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0010_auto_20250812_1721"),
        ("users", "0004_change_user_onetoone_to_fk"),
        ("worktime", "0005_add_location_and_break_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailypayrollcalculation",
            options={
                "ordering": ["-work_date", "worklog_id"],
                "verbose_name": "Daily Payroll Calculation",
                "verbose_name_plural": "Daily Payroll Calculations",
            },
        ),
        migrations.AlterUniqueTogether(
            name="dailypayrollcalculation",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="dailypayrollcalculation",
            name="worklog",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to specific shift (WorkLog). Null for daily summary records.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payroll_calculations",
                to="worktime.worklog",
            ),
        ),
        migrations.AddIndex(
            model_name="dailypayrollcalculation",
            index=models.Index(
                fields=["worklog"], name="payroll_dai_worklog_623950_idx"
            ),
        ),
    ]
