# Generated by Django 5.1.6 on 2025-08-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0011_add_worklog_to_payroll_calculation"),
        ("users", "0004_change_user_onetoone_to_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="salary",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this salary configuration is currently active",
            ),
        ),
        migrations.AddConstraint(
            model_name="salary",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("employee",),
                name="unique_active_salary_per_employee",
            ),
        ),
    ]
