# Generated by Django 5.1.6 on 2025-08-29 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0012_salary_is_active_and_more"),
        ("users", "0004_change_user_onetoone_to_fk"),
    ]

    operations = [
        # Temporarily disabled to avoid constraint issues during development
        # migrations.AlterField(
        #     model_name="salary",
        #     name="employee",
        #     field=models.ForeignKey(
        #         on_delete=django.db.models.deletion.CASCADE,
        #         related_name="salaries",
        #         to="users.employee",
        #     ),
        # ),
    ]