# Generated by Django 5.1.6 on 2025-09-05 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0013_alter_salary_employee"),
    ]

    operations = [
        # Rename payment fields to clarify their relationship to base_pay and bonus_pay
        migrations.RenameField(
            model_name='dailypayrollcalculation',
            old_name='regular_pay',
            new_name='base_regular_pay',
        ),
        migrations.RenameField(
            model_name='dailypayrollcalculation',
            old_name='overtime_pay_1',
            new_name='bonus_overtime_pay_1',
        ),
        migrations.RenameField(
            model_name='dailypayrollcalculation',
            old_name='overtime_pay_2',
            new_name='bonus_overtime_pay_2',
        ),
        migrations.RenameField(
            model_name='dailypayrollcalculation',
            old_name='sabbath_overtime_pay_1',
            new_name='bonus_sabbath_overtime_pay_1',
        ),
        migrations.RenameField(
            model_name='dailypayrollcalculation',
            old_name='sabbath_overtime_pay_2',
            new_name='bonus_sabbath_overtime_pay_2',
        ),
    ]
