# Generated by Django 5.1.10 on 2025-09-05 21:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0014_auto_20250906_0008'),
        ('users', '0004_change_user_onetoone_to_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypayrollcalculation',
            name='base_regular_pay',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Regular pay component of base_pay', max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailypayrollcalculation',
            name='bonus_overtime_pay_1',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='First 2 overtime hours at 125% - component of bonus_pay', max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailypayrollcalculation',
            name='bonus_overtime_pay_2',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Additional overtime hours at 150% - component of bonus_pay', max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailypayrollcalculation',
            name='bonus_sabbath_overtime_pay_1',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Payment for first 2 sabbath overtime hours at 175% - component of bonus_pay', max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailypayrollcalculation',
            name='bonus_sabbath_overtime_pay_2',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Payment for additional sabbath overtime hours at 200% - component of bonus_pay', max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailypayrollcalculation',
            name='total_pay',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='DEPRECATED - use total_gross_pay instead', max_digits=10),
        ),
        migrations.AlterField(
            model_name='salary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='users.employee'),
        ),
    ]
