# Generated by Django 5.1.6 on 2025-09-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0015_alter_dailypayrollcalculation_base_regular_pay_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailypayrollcalculation",
            name="calculated_by_service",
            field=models.CharField(default="PayrollService", max_length=50),
        ),
    ]
