# Generated by Django 5.1.6 on 2025-09-06 22:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0016_alter_dailypayrollcalculation_calculated_by_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailypayrollcalculation",
            name="total_salary",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Total salary amount for this calculation period",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="monthlypayrollsummary",
            name="proportional_monthly",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Proportional monthly salary based on hours worked",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="monthlypayrollsummary",
            name="total_salary",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Total salary amount for the month",
                max_digits=12,
            ),
        ),
    ]
