# Generated by Django 5.1.6 on 2025-09-08 18:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0017_add_missing_model_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlypayrollsummary",
            name="total_bonuses_monthly",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Total bonus payments for monthly employees (overtime, sabbath, etc.)",
                max_digits=12,
            ),
        ),
    ]
