# Generated by Django 5.1.6 on 2025-09-08 19:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0018_monthlypayrollsummary_total_bonuses_monthly"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailypayrollcalculation",
            name="proportional_monthly",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Proportional monthly salary portion for this calculation",
                max_digits=12,
            ),
        ),
    ]
