# Generated by Django 5.1.6 on 2025-03-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('is_shabbat', models.BooleanField(default=False)),
                ('is_holiday', models.BooleanField(default=True)),
            ],
        ),
    ]
