# Generated by Django 5.1.6 on 2025-03-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ['-date'], 'verbose_name': 'Holiday', 'verbose_name_plural': 'Holidays'},
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
