# Generated by Django 5.1.6 on 2025-03-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_alter_holiday_options_alter_holiday_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
