# Generated by Django 5.1.6 on 2025-03-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_holiday_end_time_holiday_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='is_special_shabbat',
            field=models.BooleanField(default=False),
        ),
    ]
